spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/h2/o3o
    username: sa
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
